version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    depends_on:
      - mongo
    environment:
      - MONGO_CLIENT=mongodb://mongo:27017/
      - DEBUG=True  # Debug environment variable

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
